object Versions {
    const val agp = "8.7.2"
    const val kotlin = "2.0.0"
    const val coreKtx = "1.15.0"
    const val junit = "4.13.2"
    const val junitVersion = "1.2.1"
    const val espressoCore = "3.6.1"
    const val lifecycleRuntimeKtx = "2.8.7"
    const val activityCompose = "1.9.3"
    const val composeBom = "2024.04.01"
    const val coroutines= "1.3.9"
    const val hiltGradlePluginVersion = "2.47"
    const val hilt = "2.51.1"
    const val hiltNavigationCompose = "1.2.0"
    const val lifecycle_version = "2.8.7"
    const val constraintlayout = "1.1.0"
    const val room_version = "2.6.1"
    const val retrofit = "2.9.0"
    const val moshi = "1.14.0"
    const val okhttp = "4.11.0"
    const val coil = "2.2.2"
    const val pagin = "3.3.4"
    const val dataStore = "1.1.1"
    const val nav_version = "2.8.5"
    const val kotlin_serialization =  "2.1.0"

    const val hamcrest = "1.3"
    const val arch_core_testing = "1.1.1"
    const val mockito = "3.9.0"
    const val mockito_android = "3.4.6"
    const val mockk = "1.13.2"
    const val turbine = "1.0.0"
    const val android_test_core = "1.6.1"
    const val coroutines_test = "1.6.4"
    const val compose = "1.7.5"

}

